package nl.veldhvz.conditionals.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import jetbrains.mps.baseLanguage.behavior.IVariableReference__BehaviorDescriptor;

public class SubjectReference_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    _context.getBuilder().emitRead(IVariableReference__BehaviorDescriptor.getVariable_idSORzhOpB6t.invoke(_context.getNode()), "r:44bbab81-e87f-49da-9a1a-45802043bed6(nl.veldhvz.conditionals.dataFlow)/3116594940450508683");
  }
}
